### PR TITLE
Workaround for MAC Support

### PR DESCRIPTION
**Pull request by finneyj**
- added state variable to prevent rendering of a frame before a JFXPanel is
   attached to a JFrame.

### CODE REVIEW

**Comment by marvin-kopo** [comment]
Hi Joe,
I am not on my MAC now...I can try to check the version later.

About my code, I didnt do anything much.

``` public class Driver{
  public static void main(String[] args) {
  	RacerGame rg = new RacerGame();
  }
}```

```import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class RacerGame{
	public int SCREEN_WIDTH = 600;
	public int SCREEN_HEIGHT = 600;
	
	Racer r = new Racer();
	
	JFrame window = new JFrame();
	private JPanel mainPanel = new JPanel();
	private JPanel buttonPanel = new JPanel();
	private JPanel scorePanel = new JPanel();

	FlowLayout mainLayout = new FlowLayout();

	public RacerGame(){
		
        mainPanel.setLayout(mainLayout);

        mainPanel.add(r.getPanel());
        mainPanel.add(scorePanel);   
        mainPanel.add(buttonPanel);

        window.setTitle("Racer");
        window.setSize(SCREEN_WIDTH, SCREEN_HEIGHT);
        window.setContentPane(mainPanel);
        window.setVisible(true);

        r.start();

        while(r.isPlaying())
            r.update();
	}
}```

**Comment by finneyj** [comment]
ta - code looks fine. 

MAC implementation of Java is rather flaky compared to other OS... if you're not on the latest version, cna you try an update?

**Comment by marvin-kopo** [comment]
No problem thanks.
I suspect that might be the problem. I dont remember updating it lately.

**Comment by marvin-kopo** [comment]
Still nothing...

Java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

MacOS Sierra
Version: 10.12.3 (16D32)

**Pull request merged**
